[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run server"
healthcheckPath = "/api/assistants"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 